### ISSUE TITLE
Bundle Install not working.

### ISSUE THREAD

**Issue by andrewtpoe** [knu/ruby-unf_ext#13]
I am attempting to set up Stripe on a website I am building. unf_ext is installed as a dependency for their gem. I encountered the error below. It duplicates when I try to install unf_ext as a standalone gem as well. When running bundle install I receive this error: 

```
/Users/me/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20151006-77029-11oqg9a.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/techapoe/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/techapoe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:6:in `<main>'

extconf failed, exit code 1
```

I am using OS X 10.11. I have x-code installed and updated. Help is appreciated!

**Comment by andrewtpoe** [comment]
This issue occurred after upgrading OS X to 10.11. I was unaware that I would have to re-agree to x-codes terms and conditions. After completing the agreement process I am able to install without apparent issue.
