### ISSUE TITLE
Gem install fails for 2.2.3-clang

### ISSUE THREAD

**Issue by full-of-foo** [knu/ruby-unf_ext#16]
On OS X 10.11.3 installing `unf_ext` fails under CRuby `2.2.3-clang` fails from not having system-level dependencies:

```
» rvm use ruby-2.2.3-clang
Using /Users/pewpewpew/.rvm/gems/ruby-2.2.3-clang
Anthonys-MacBook-Pro :: Documents/lol/catz ‹wip› » gem install gooddata
Building native extensions.  This could take a while...
ERROR:  Error installing gooddata:
	ERROR: Failed to build gem native extension.

    /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/bin/ruby -r ./siteconf20160214-65070-41cxnb.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/pewpewpew/.rvm/rubies/ruby-2.2.3-clang/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/pewpewpew/.rvm/gems/ruby-2.2.3-clang/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /Users/pewpewpew/.rvm/gems/ruby-2.2.3-clang/extensions/x86_64-darwin-14/2.2.0-static/unf_ext-0.0.7.2/gem_make.out
```

However, this is *not* the case on standard CRuby ` 2.2.3`, unf_ext installs fine

**Comment by mikeshultz** [comment]
Looks like some development tools like gcc need to be installed.  On CentOS: `yum groupinstall "Development Tools`.  Sorry, not sure about OSX.

Ref: https://github.com/sensu-plugins/sensu-plugins-http/issues/51

**Comment by yakimant** [comment]
@mikeshultz
OSX: xcode-select --install
